# Generated by Django 6.1.1 on 2026-09-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='Device ID')),
                ('local_key', models.CharField(max_length=64, verbose_name='Local Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP local')),
                ('version', models.CharField(choices=[('3.1', '3.1'), ('3.3', '3.3'), ('3.4', '3.4')], default='3.3', max_length=4, verbose_name='Versión de protocolo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Ampolleta',
                'verbose_name_plural': 'Ampolletas',
                'ordering': ['name'],
            },
        ),
    ]
