# Generated by Django 6.1.1 on 2026-09-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP local'),
        ),
    ]
