# Generated by Django 6.1.1 on 2026-09-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulbs', '0002_alter_bulb_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulb',
            name='version',
            field=models.CharField(choices=[('3.1', '3.1'), ('3.3', '3.3'), ('3.4', '3.4'), ('3.5', '3.5')], default='3.3', max_length=4, verbose_name='Versión de protocolo'),
        ),
    ]
