# Generated by Django 6.1.1 on 2026-09-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulbs', '0003_alter_bulb_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('days_of_week', models.CharField(help_text='0=Lunes ... 6=Domingo, separados por coma', max_length=20, verbose_name='Días')),
                ('start_time', models.TimeField(verbose_name='Desde')),
                ('end_time', models.TimeField(verbose_name='Hasta')),
                ('color_a', models.CharField(default='#ff0000', max_length=7, verbose_name='Color A')),
                ('color_b', models.CharField(default='#0000ff', max_length=7, verbose_name='Color B')),
                ('min_interval_minutes', models.PositiveIntegerField(default=5, verbose_name='Intervalo mínimo (min)')),
                ('max_interval_minutes', models.PositiveIntegerField(default=15, verbose_name='Intervalo máximo (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('in_window', models.BooleanField(default=False)),
                ('last_color', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=1, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('bulb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bulbs.bulb', verbose_name='Ampolleta')),
            ],
            options={
                'verbose_name': 'Programación de color',
                'verbose_name_plural': 'Programaciones de color',
                'ordering': ['bulb__name', 'start_time'],
            },
        ),
    ]
